### ISSUE TITLE
[ICDM] UI-automation commissioning is failing on the RPI platform using lit-icd-app.

### ISSUE THREAD

**Issue by Rajashreekalmane** [project-chip/certification-tool#153] opened 2024-01-24 12:58 UTC
### Describe the bug
[ICDM] UI-automation commissioning is failing on the RPI platform using lit-icd-app.

![image](https://github.com/project-chip/certification-tool/assets/95841834/dad0972c-1732-470c-8f1c-c3e105932cd8)

### Steps to reproduce the behavior

1. Open the UI
2. Upload the PICS
3. Ensure the TC-ICDM-1.1 test case is selected
4. Executed the below mentioned command to put DUT into a commissionable state,
5.  ./lit-icd-app
6. Click the Start button on Test-Harness user interface.

Version: 2.10-beta2.1+spring2024
Sha: 549e33f

**Comment by ccruzagralopes** [comment] 2024-01-30 17:04
Hello @Rajashreekalmane, can you please provide the test case logs?

**Comment by ccruzagralopes** [comment] 2024-02-01 14:09
From the logs, the error was `Buffer too small`:

```
CHIPTOOL   | 2024-01-31 09:12:39.737054 | CHIP:TOO Failed to persist symmetric key for E6E3853A0978F865: src/lib/core/TLVWriter.cpp:846: CHIP Error 0x00000019: Buffer too small
CHIPTOOL   | 2024-01-31 09:12:39.738022 | CHIP:TOO Run command failure: src/lib/core/TLVWriter.cpp:846: CHIP Error 0x00000019: Buffer too small
```

This seems like an error in the pairing between the DUT and the `chip-tool` binary, not related to the TH.
@cecille can you help with this issue?

**Comment by cecille** [comment] 2024-02-05 18:27
This might actually be a TH problem - there's only so much space on the commissioner to store keys. If you've commissioned a bunch of devices, you'll run out of space.

Does this error occur if the lit-icd app is the FIRST one you test?

**Comment by Rajashreekalmane** [comment] 2024-02-20 05:47
@cecille we have commissioned only lit-icd-app , even though facing the issue after clearing the tmp files

**Comment by ccruzagralopes** [comment] 2024-02-21 17:23
> This might actually be a TH problem - there's only so much space on the commissioner to store keys. If you've commissioned a bunch of devices, you'll run out of space.

@cecille TH destroys the SDK container after each test suite execution, so each time you execute the test cases you get a "clean" container, without previously stored keys.

**Comment by dvdm-qorvo** [comment] 2024-06-06 19:13
We are hitting the same issue with our LIT ICD device... It looks like it is not able to store the combination of the big nodeId number (generated by the harness) and the symmetric key. If you executed chiptool with a small nodeId number (1 for example), this error can't be reproduced

**Comment by antonio-amjr** [comment] 2024-06-13 13:50
Hi @Rajashreekalmane and @dvdm-qorvo 

It seems that your theory @dvdm-qorvo about the nodeID number size proceeds.
I did reproduce the behavior with the 64 random bits number and I also managed to commit successfully with a smaller nodeID.

Looking at the code, I suppose the problem is with the `MaxICDClientInfoSize()` method from the SDK's `DefaultICDClientStorage.h` file is not correct.
But the `good news` is that the a fix is already merged in the SDK's code (from a [commit](https://github.com/project-chip/connectedhomeip/commit/1404f807cc476fa2afa267de0f88d5a85881da61) some time ago) and the fall2024 beta version of TH is already using a SDK with the relevant change for this.

I already tested here and everything seems fine.
Is it possible for you guys @dvdm-qorvo and @Rajashreekalmane test as well the `v2.11-beta2+fall2024` branch and verify if it solves this issue?

Let me know any news,
Thanks

**Comment by antonio-amjr** [comment] 2024-06-13 17:33
@dvdm-qorvo,

Since you're pursuing a certification round of tests, I believe a formal patch release will be necessary.
But I'm not the best person to answer that. What I recommend is for you to ask this to someone in the certification team.
I think the CSA Slack channel `general-matter-wg` is a good start point.

**PS:** Thanks for the feedback

**Comment by antonio-amjr** [comment] 2024-07-30 13:20
I believe we don't need further investigation on this and the current `fall2024` seems to already solve this issue.
Since the only questions left is related to the certification process, I'm closing this up.

**Closed as completed by antonio-amjr** 2024-07-30 13:20 UTC
Labels: Awaiting Originator Feedback
