### ISSUE TITLE
[Bug] TestHarness on Linux: CHIP: BLE: No adaptor

### ISSUE THREAD

**Issue by jscarey1** [project-chip/certification-tool#158] opened 2024-01-26 16:03 UTC
### Describe the bug

Attempting to use chip-tool packaged in TH.
chip-tool fails to begin commissioning due to `No Adapter Available`

### Log files

[1706218624.215723][3475:3477] CHIP:CTL: Setting wifi credentials from parameters
[1706218624.215755][3475:3477] CHIP:CTL: Setting attestation nonce to random value
[1706218624.215768][3475:3477] CHIP:CTL: Setting CSR nonce to random value
[1706218624.215777][3475:3477] CHIP:CTL: Checking ICD registration parameters
[1706218624.215786][3475:3477] CHIP:CTL: Commission called for node ID 0x0000000000000001
[1706218624.215799][3475:3477] CHIP:DIS: Closing all BLE connections
[1706218624.215825][3475:3477] CHIP:TOO: Pairing Failure: src/platform/Linux/BLEManagerImpl.cpp:664: CHIP Error 0x00000003: Incorrect state
[1706218624.215837][3475:3477] CHIP:TOO: Run command failure: src/platform/Linux/BLEManagerImpl.cpp:664: CHIP Error 0x00000003: Incorrect state
[1706218624.215851][3475:3477] CHIP:BLE: No adapter available for new connection establishment

### Environment

TH = v2.10-beta2+spring2024

**Comment by ccruzagralopes** [comment] 2024-01-29 19:38
Hi @jscarey1,
I believe that the error was actually caused by an `Incorrect state`.
Was the device being commissioned in commissioning mode at the time?

**Comment by jscarey1** [comment] 2024-01-29 19:49
Hello Carlina,
Yes the DUT was advertising for Matter over BLE.

On a side note,
I am attempting to build Test Harness on a Linux PC (Ubuntu 22.04 LTS) so
that I can use the python environment for testing.
The environment I am looking to use is outlined in the
Matter_TH_User_Guide.adoc section 8.5.
On a raspberry pi I can build this with no issue and create custom python
scripts that will test all of our implementations. I was hoping, however,
to accomplish this without the need to rely on a raspberry pi.

Even better, is there a way to build just the python environment for
automated python testing on a Linux system.
We are looking to run nightly automated tests that are kicked off by a
Jenkins pipeline.
Each Cluster, Attribute, Command would be tested in this scenario.

**Comment by ccruzagralopes** [comment] 2024-01-30 12:09
I believe you can achieve that using the [SDK repository](https://github.com/project-chip/connectedhomeip/) directly. That's where they python test scripts are hosted and you can run them directly in there, without TH.
Maybe @cecille can help you with the setup?

**Comment by jscarey1** [comment] 2024-01-30 20:35
@cecille
Is this something you could assist with?

**Comment by ccruzagralopes** [comment] 2024-02-05 14:49
Maybe you can open an issue in the SDK repository or transfer this one over there. There could be more people over there that has the knowledge you need.

**Comment by fabiowmm** [comment] 2024-11-14 12:33
Closing as this is not actually TH.

**Closed by fabiowmm** 2024-11-14 12:33 UTC
Labels: Blocked
